name: CI/CD

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
